export const images = [
    { image: require('./1.jpg') },
    { image: require('./2.jpg') },
    { image: require('./3.jpg') },
    { image: require('./4.jpg') },
    { image: require('./5.jpg') },
    { image: require('./6.jpg') },
    { image: require('./7.jpg') },
    { image: require('./8.jpg') },
    { image: require('./9.jpg') },
    { image: require('./10.jpg') },
    { image: require('./11.jpg') },
    { image: require('./12.jpg') },
    { image: require('./13.jpg') },
    { image: require('./14.jpg') },
    { image: require('./15.jpg') },
    { image: require('./16.jpg') },
    { image: require('./17.jpg') },
    { image: require('./18.jpg') },
    { image: require('./19.jpg') },
    { image: require('./20.jpg') },
];